name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2

      - name: Code Quality
        run: poetry run black . --check

      - name: Test with pytest
        run: |
          poetry run flake8
          poetry run coverage run -m unittest discover -b
